export const navigationLinks = [
  { name: 'Home', route: '/', icon: 'home', desc: '' },
  { name: 'Button', route: 'button-demo', icon: 'code', desc: 'Buttons communicate the action that will occur when the user touches them.' },
  { name: 'Card', route: 'card-demo', icon: 'credit_card', desc: 'A card is a sheet of material that serves as an entry point to more detailed information.' },
  { name: 'Checkbox', route: 'checkbox-demo', icon: 'check_box', desc: 'Checkboxes allow the user to select multiple options from a set.' },
  { name: 'Dialog', route: 'dialog-demo', icon: 'question_answer', desc: 'Dialogs inform users about a specific task, require decisions, or involve multiple tasks.' },
  { name: 'Drawer', route: 'drawer-demo', icon: 'code', desc: 'Drawers slide in from the left and contains the navigation destinations for your app.' },
  { name: 'Floating Action Button (FAB)', route: 'fab-demo', icon: 'add_circle_outline', desc: 'A floating action button represents the primary action in an application.' },
  { name: 'Icon Toggle', route: 'icon-toggle-demo', icon: 'star', desc: 'Icon toggle buttons allow a single choice to be selected or deselected.' },
  { name: 'Linear-Progress', route: 'linear-progress-demo', icon: 'code', desc: 'Progress and activity indicators are visual indications of an app loading content.' },
  { name: 'List', route: 'list-demo', icon: 'list', desc: 'Lists present multiple line items vertically as a single continuous element.' },
  { name: 'Menu', route: 'menu-demo', icon: 'menu', desc: 'Menus display a list of choices on a transient sheet of material.' },
  { name: 'Radio Button', route: 'radio-demo', icon: 'radio_button_checked', desc: 'Radio buttons allow the user to select one option from a set.' },
  { name: 'Slider', route: 'slider-demo', icon: 'linear_scale', desc: 'Sliders let users select from a range of values by moving the slider thumb.' },
  { name: 'Snackbar', route: 'snackbar-demo', icon: 'info_outline', desc: 'Snackbars provide brief feedback through a message at the bottom of the screen.' },
  { name: 'Switch', route: 'switch-demo', icon: 'wb_incandescent', desc: 'On/off switches toggle the state of a single settings option.' },
  { name: 'Tabs', route: 'tab-demo', icon: 'tab', desc: 'Tabs make it easy to explore and switch between different views.' },
  { name: 'Text Field', route: 'textfield-demo', icon: 'text_fields', desc: 'Text fields allow users to input, edit, and select text.' },
  { name: 'Toolbar', route: 'toolbar-demo', icon: 'code', desc: 'Toolbars appear a step above the sheet of material affected by their actions.' },
];
